# Generated by Django 3.1.4 on 2022-01-09 15:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='should_send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_image', models.URLField(null=True)),
                ('address', models.TextField()),
                ('bin', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=5)),
                ('bin_no', models.CharField(max_length=50, null=True)),
                ('tin', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=5)),
                ('tin_no', models.CharField(max_length=50, null=True)),
                ('trade_licence', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('trade_licence_no', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profiles',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
