# Generated by Django 3.1.4 on 2022-01-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220109_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='settled_post',
            field=models.IntegerField(default=0),
        ),
    ]
