# Generated by Django 3.1.4 on 2022-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220110_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating_value',
            new_name='buyer_rating_value',
        ),
        migrations.AddField(
            model_name='user',
            name='merchant_rating_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
