# Generated by Django 3.1.4 on 2022-01-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20220110_1250'),
        ('user', '0006_auto_20220110_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='post.post'),
            preserve_default=False,
        ),
    ]
