"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from core.settings.base import *
from core.settings.apps import *
from core.settings.app_vars import *
from core.settings.logger import *
from core.settings.database import *
from core.settings.third_party import *
from core.settings.celery import *
