# Generated by Django 3.1.4 on 2022-01-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220121_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction'),
        ),
    ]
