# Generated by Django 3.1.4 on 2022-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20220121_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bkash', 'bkash'), ('nagad', 'nagad'), ('admin', 'admin')], default='admin', max_length=10),
        ),
    ]
