# Generated by Django 3.1.4 on 2022-01-06 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=3)),
                ('description', models.TextField(max_length=150)),
                ('color', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=20)),
                ('meta', models.JSONField(default=dict)),
                ('active_from', models.DateTimeField(null=True)),
                ('active_to', models.DateTimeField(null=True)),
                ('points_needed', models.PositiveIntegerField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20)),
                ('publish_status', models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished')], default='unpublished', max_length=11)),
                ('settlement_status', models.CharField(choices=[('settled', 'settled'), ('unsettled', 'unsettled')], default='unsettled', max_length=9)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'post_interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
