# Generated by Django 3.1.4 on 2022-01-06 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20220106_1154'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postinterest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_postinterests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postinterest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.post'),
        ),
        migrations.AddField(
            model_name='postinterest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_postinterests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postinterest',
            index=models.Index(fields=['username'], name='post_intere_usernam_8439bc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='posts_title_b9805f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_approved'], name='posts_is_appr_c45372_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['settlement_status'], name='posts_settlem_ab6d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publish_status'], name='posts_publish_8a2acf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['username'], name='posts_usernam_9e9a03_idx'),
        ),
    ]
