# Generated by Django 3.1.4 on 2022-01-08 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220108_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=5),
        ),
    ]
