# Generated by Django 3.1.4 on 2022-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220108_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_interest',
            field=models.IntegerField(default=0),
        ),
    ]
