# Generated by Django 3.1.4 on 2022-01-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20220109_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='post',
            name='active_to',
        ),
    ]
