# Generated by Django 3.1.4 on 2022-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlepost',
            name='settled_by',
        ),
        migrations.AlterField(
            model_name='settlepost',
            name='settlement_date',
            field=models.DateField(),
        ),
    ]
