# Generated by Django 3.1.4 on 2022-01-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_auto_20220110_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinterest',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='PostConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_postconfigs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_postconfigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postconfig',
            index=models.Index(fields=['-created_at'], name='post_config_created_298467_idx'),
        ),
    ]
